example:
  field: value
cloud:
  config:
    client:
      file:
        resources:
          - directory: temp
            files:
              - temp1.json
              - temp2.yml
              - temp3.properties
#         enabled: true
