example:
  field: value
cloud:
  config:
    client:
      file:
        resources:
          - directory: temp/
            files:
              - temp1.json
              - temp2.json
              - temp3.json
              - temp4.json
              - temp5.json
              - temp6.json
              - temp7.json
              - temp8.json
              - temp9.json
              - temp10.json
              - temp20.yml
              - temp21.properties
              - list1.json
              - list2.json
              - list3.json
              - list4.json
              - list5.json
          - directory: temp/anothertemp
            files:
              - testing.json
              - testing1.json
              - testing2.json
              - testing3.json
              - testing4.json
